#Shopify page
CREATE_START_TRIAL_BTN = '//a[contains(text(),"Start free trial")]'
SKIP_BTN = '//span[text()="Skip All"]'
NEXT_BTN_1 = '(//span[text()="Next"])[2]'
INPUT_STORE_NAME = '//input[@id="storeName"]'
NEXT_BTN_2 = '/html/body/div[1]/div/div[1]/div/div/main/div/div[2]/div[3]/div/div/div/form/nav/div/div[3]/button'
NEXT_BTN_3 = '/html/body/div[1]/div/div[1]/div/div/main/div/div[2]/div[3]/div/div/div/nav/div/div[2]/button'
CONTINUE_WITH_EMAIL_BTN = '(//div[@class="account-picker__item-content account-picker__action content"])[1]'
INPUT_EMAIL = '//input[@id="account_email"]'
INPUT_PASS = '//input[@id="account_password"]'
CREATE_SHOPIFY_ID_BTN = '//*[@id="submit-disable"]/button'
ADD_APPS_BTN = '//button[contains(.,"Add apps")]'
SHOPIFY_APP_STORE_BTN = '//a[@class="Polaris-Link Polaris-Link--removeUnderline" and contains(text(),"Shopify App Store")]' 
SEARCH_APPS_TEXTBOX = '(//input[@type="search"])[1]'
PAGE_BTN = '(//a[contains(text(),"3")])[3]'
SELECT_APP = '//a[contains(text(),"Promofy: Flash sale & Discount")]'
# SELECT_APP_NOT_AD = '//a[contains(text(),"PageFly Landing Page Builder") and not(contains(@href,"search_ad"))]'
# SELECT_APP_AD = '//a[contains(text(),"PageFly Landing Page Builder") and (contains(@href,"search_ad"))]'
# ADD_APP_SHOPIFY_BTN = '(//button[@type="submit" and contains(., "Add app")])'
ADD_APP_SHOPIFY_BTN = '(//button[@type="submit"])[6]'
# INSTALL_APP_BTN = '(//button[@type="button" and contains(., "Install app")])'
INSTALL_APP_BTN = '//*[@id="proceed_cta"]'

IFRAME = '//*[@id="search_page"]'
SKIP_HELP_BTN = '/html/body/div/div/div/div/div/div/div/div/div/button'
