#Shopify page
CREATE_START_TRIAL_BTN = '//a[contains(text(),"Start free trial")]'
SKIP_BTN = '//*[@id="navigation-skip-all-button"]/span/span'
NEXT_BTN_1 = '(//button[@id="navigation-next-button"])[1]'
INPUT_STORE_NAME = '//input[@id="storeName"]'
NEXT_BTN_2 = '/html/body/div[1]/div/div[1]/div/div/main/div/div[2]/div[3]/div/div/div/form/nav/div/div[3]/button'
NEXT_BTN_3 = '/html/body/div[1]/div/div[1]/div/div/main/div/div[2]/div[3]/div/div/div/nav/div/div[2]/button'
CONTINUE_WITH_EMAIL_BTN = '//body[@id="body-content"]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/a'
INPUT_EMAIL = '//input[@id="account_email"]'
INPUT_PASS = '//input[@id="account_password"]'
CREATE_SHOPIFY_ID_BTN = '//*[@id="submit-disable"]/button'
ADD_APPS_BTN = '//*[@id="AppFrameNav"]/div/nav/div[2]/ul/li[2]/div[2]/button'
SHOPIFY_APP_STORE_BTN = '/html/body/div/div[2]/div[11]/div[1]/div/div/div/div/div[2]/div[4]/p/a' 
SEARCH_APPS_TEXTBOX = '//*[@id="search_suggestions_container"]/div[1]/div/input[1]'
PAGE_BTN = '(//a[contains(text(),"3")])[3]'
SELECT_APP = '//a[contains(text(),"Promofy: Flash sale & Discount")]'
# SELECT_APP_NOT_AD = '//a[contains(text(),"PageFly Landing Page Builder") and not(contains(@href,"search_ad"))]'
# SELECT_APP_AD = '//a[contains(text(),"PageFly Landing Page Builder") and (contains(@href,"search_ad"))]'
ADD_APP_SHOPIFY_BTN = '(//button[@type="submit" and contains(., "Add app")])'
INSTALL_APP_BTN = '(//button[@type="button" and contains(., "Install app")])'
IFRAME = '//*[@id="search_page"]'
